version: '3.8'

services:
  # Servizio ETL
  etl:
    image: localhost/olist_app:latest
    volumes:
      - ../data:/app/data
    environment:
      - PYTHONPATH=/app
      - DB_PATH=data/warehouse.duckdb
    command: python etl/flows/main_flows.py
    restart: "no"

  # Servizio Dashboard
  dashboard:
    image: localhost/olist_app:latest
    ports:
      - "8501:8501"
    volumes:
      - ../data:/app/data
    environment:
      - DB_PATH=data/warehouse.duckdb
    restart: always
    depends_on:
      etl:
        condition: service_completed_successfully